nav:
    - man-7-pthreads: man-7-pthreads.md
    - man-7-attributes: man-7-attributes.md
    - Thread-model: Thread-model.md
    - Thread-creation: Thread-creation.md
    - Thread-termination: Thread-termination.md
    - Synchronization: Synchronization
