edit_uri: ''
extra_css:
- css/extra.css
google_analytics:
- UA-27795084-5
- mkdocs.org
nav:
- Home: index.md
- "Operating-system-\u6982\u8FF0": Operating-system.md
- Unix-standardization-and-implementation: Unix-standardization-and-implementation.md
- Unix-&-Unix-like-&-Linux: Unix-&-Unix-like-&-Linux.md
- Architecture:
  - Architecture-of-computing-system: Architecture/Architecture-of-computing-system.md
- Kernel:
  - Introduction: Kernel/index.md
  - Kernel: Kernel/Kernel(operating-system).md
  - book-Understanding-the-Linux-Kernel:
    - Introduction: Kernel/book-Understanding-the-Linux-Kernel/index.md
    - Chapter-1-Introduction:
      - Chapter-1-Introduction: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/Chapter-1-Introduction.md
      - 1.1-Linux-Versus-Other-Unix-Like-Kernels: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.1-Linux-Versus-Other-Unix-Like-Kernels.md
      - 1.2-Hardware-Dependency: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.2-Hardware-Dependency.md
      - 1.4-Basic-Operating-System-Concepts: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.4-Basic-Operating-System-Concepts.md
      - 1.6-An-Overview-of-Unix-Kernels: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6-An-Overview-of-Unix-Kernels.md
      - 1.6.1-The-Process-Kernel-Model: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.1-The-Process-Kernel-Model.md
      - 1.6.2-Process-Implementation: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.2-Process-Implementation.md
      - 1.6.3-Reentrant-Kernels: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.3-Reentrant-Kernels.md
      - 1.6.4-Process-Address-Space: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.4-Process-Address-Space.md
      - 1.6.5-Synchronization-and-Critical-Regions: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.5-Synchronization-and-Critical-Regions.md
      - 1.6.6-Signals-and-Interprocess-Communication: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.6-Signals-and-Interprocess-Communication.md
      - 1.6.7-Process-Management: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.7-Process-Management.md
      - 1.6.8-Memory-Management: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.8-Memory-Management.md
      - 1.6.9-Device-Drivers: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.9-Device-Drivers.md
      - Giant-lock: Kernel/book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/Giant-lock.md
    - Chapter-2-Memory-Addressing:
      - Chapter-2-Memory-Addressing: Kernel/book-Understanding-the-Linux-Kernel/Chapter-2-Memory-Addressing/Chapter-2-Memory-Addressing.md
      - 2.1-Memory-Addresses: Kernel/book-Understanding-the-Linux-Kernel/Chapter-2-Memory-Addressing/2.1-Memory-Addresses.md
      - 2.4-Paging-in-Hardware: Kernel/book-Understanding-the-Linux-Kernel/Chapter-2-Memory-Addressing/2.4-Paging-in-Hardware.md
      - 2.5-Paging-in-Linux: Kernel/book-Understanding-the-Linux-Kernel/Chapter-2-Memory-Addressing/2.5-Paging-in-Linux.md
    - Chapter-3-Processes:
      - Chapter-3-Processes: Kernel/book-Understanding-the-Linux-Kernel/Chapter-3-Processes/Chapter-3-Processes.md
      - 3.1-Processes-and-Lightweight-Processes-and-Threads: Kernel/book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.1-Processes-and-Lightweight-Processes-and-Threads.md
      - 3.2-Process-Descriptor: Kernel/book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2-Process-Descriptor.md
      - 3.2.2-Identifying-a-Process: Kernel/book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.2-Identifying-a-Process.md
      - 3.4-Creating-Processes: Kernel/book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.4-Creating-Processes.md
      - Copy-on-write: Kernel/book-Understanding-the-Linux-Kernel/Chapter-3-Processes/wikipedia-Copy-on-write.md
    - Chapter-4-Interrupts-and-Exceptions:
      - Chapter-4-Interrupts-and-Exceptions: Kernel/book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/Chapter-4-Interrupts-and-Exceptions.md
      - 4.1-The-Role-of-Interrupt-Signals: Kernel/book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.1-The-Role-of-Interrupt-Signals.md
      - 4.2-Interrupts-and-Exceptions: Kernel/book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.2-Interrupts-and-Exceptions.md
      - 4.3-Nested-Execution-of-Exception-and-Interrupt-Handlers: Kernel/book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.3-Nested-Execution-of-Exception-and-Interrupt-Handlers.md
      - 4.6-Interrupt-Handling: Kernel/book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.6-Interrupt-Handling.md
    - Chapter-6-Timing-Measurements:
      - Chapter-6-Timing-Measurements: Kernel/book-Understanding-the-Linux-Kernel/Chapter-6-Timing-Measurements/Chapter-6-Timing-Measurements.md
    - Chapter-7-Process-Scheduling:
      - Chapter-7-Process-Scheduling: Kernel/book-Understanding-the-Linux-Kernel/Chapter-7-Process-Scheduling/Chapter-7-Process-Scheduling.md
    - Chapter-8-Memory-Management:
      - Chapter-8-Memory-Management: Kernel/book-Understanding-the-Linux-Kernel/Chapter-8-Memory-Management/Chapter-8-Memory-Management.md
      - 8.1-Page-Frame-Management: Kernel/book-Understanding-the-Linux-Kernel/Chapter-8-Memory-Management/8.1-Page-Frame-Management.md
    - Chapter-9-Process-Address-Space:
      - Chapter-9-Process-Address-Space: Kernel/book-Understanding-the-Linux-Kernel/Chapter-9-Process-Address-Space/Chapter-9-Process-Address-Space.md
      - 9.1-The-Process's-Address-Space.: Kernel/book-Understanding-the-Linux-Kernel/Chapter-9-Process-Address-Space/9.1-The-Process's-Address-Space.md
      - 9.2-The-Memory-Descriptor: Kernel/book-Understanding-the-Linux-Kernel/Chapter-9-Process-Address-Space/9.2-The-Memory-Descriptor.md
    - Summary:
      - How-to-understand-linux-kernel-source-code: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-to-understand-linux-kernel-source-code.md
      - How-OS-run-01-OS-kernel-is-event-driven: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-OS-run-01-OS-kernel-is-event-driven.md
      - How-OS-run-02-kernel-control-path-and-reentrant-kernel: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-OS-run-02-kernel-control-path-and-reentrant-kernel.md
      - How-OS-run-03-Control-path-&-Context-&-Context-switch: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-OS-run-03-Control-path-&-Context-&-Context-switch.md
      - How-OS-run-04-multitask: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-OS-run-04-multitask.md
      - How-OS-run-05-process-model: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-OS-run-05-process-model.md
      - How-OS-run-06-process-address-space: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-OS-run-06-process-address-space.md
      - How-OS-run-07-thread: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-OS-run-07-thread.md
      - How-OS-run-08-Entry-point-of-kernel: Kernel/book-Understanding-the-Linux-Kernel/Summary/How-OS-run-08-Entry-point-of-kernel.md
      - VS-process-VS-thread-VS-lightweight-process: Kernel/book-Understanding-the-Linux-Kernel/Summary/VS-process-VS-thread-VS-lightweight-process.md
      - Debugger: Kernel/book-Understanding-the-Linux-Kernel/Summary/Debugger.md
- Programming:
  - Introduction: Programming/index.md
  - Convention:
    - Conventions: Programming/01-01-Convention/Conventions.md
  - Lib:
    - GNU:
      - Introduction: Programming/01-02-Lib/organization-gnu/index.md
      - Autoconf:
        - Autoconf: Programming/01-02-Lib/organization-gnu/Autoconf/Autoconf.md
      - Automake:
        - Automake: Programming/01-02-Lib/organization-gnu/Automake/Automake.md
      - Autotools-Mythbuster:
        - Introduction: Programming/01-02-Lib/organization-gnu/Autotools-Mythbuster/index.md
    - POSIX:
      - Introduction: Programming/01-02-Lib/organiztion-posix/index.md
  - Common:
    - Time-and-space: Programming/01-03-Common/Unix-programming-time-and-space.md
    - System-call: Programming/01-03-Common/Unix-system-call.md
    - Safety: Programming/01-03-Common/safety.md
    - Capabilities: Programming/01-03-Common/Capabilities.md
    - Path-resolution: Programming/01-03-Common/Path-resolution.md
  - Philosophy:
    - Introduction: Programming/01-philosophy/index.md
    - Unix-philosophy-everything-is-a-file: Programming/01-philosophy/Unix-philosophy-Everything-is-a-file.md
    - File-descriptor: Programming/01-philosophy/File-descriptor.md
    - Unix-philosophy: Programming/01-philosophy/Unix-philosophy.md
  - Process:
    - Introduction: Programming/02-Process/index.md
    - IPC:
      - System-V-IPC:
        - System-V-IPC: Programming/02-Process/IPC/System-V-IPC/System-V-IPC.md
      - POSIX-semaphores: Programming/02-Process/IPC/POSIX-semaphores.md
      - POSIX-message-queues: Programming/02-Process/IPC/POSIX-message-queues.md
    - Thread:
      - pthreads: Programming/02-Process/Thread/pthreads.md
  - IO:
    - Introduction: Programming/03-IO/index.md
  - Time:
    - Introduction: Programming/03-Time/index.md
  - Signal:
    - Introduction: Programming/04-Signal/index.md
  - Virtualization:
    - Introduction: Programming/05-Linux-Virtualization/index.md
    - Virtualization: Programming/05-Linux-Virtualization/Virtualization.md
    - Linux-containers: Programming/05-Linux-Virtualization/Linux-containers.md
    - Linux-namespaces:
      - Introduction: Programming/05-Linux-Virtualization/Linux-namespaces/index.md
      - Linux-Namespaces: Programming/05-Linux-Virtualization/Linux-namespaces/Linux-Namespaces.md
      - man-7-namespaces: Programming/05-Linux-Virtualization/Linux-namespaces/man-7-namespaces.md
    - Linux-control-groups:
      - Introduction: Programming/05-Linux-Virtualization/Linux-control-groups/Control-groups.md
  - Util:
    - Introduction: Programming/06-Util/index.md
    - Log:
      - Linux-log-files: Programming/06-Util/Log/Linux-log-files.md
      - Syslog:
        - Syslog: Programming/06-Util/Log/Syslog/Syslog.md
  - Kernel-module:
    - Loadable-kernel-module: Programming/07-Linux-Kernel-module/Loadable-kernel-module.md
  - Shell:
    - Dmesg:
      - Dmesg: Programming/08-Shell/Dmesg/Dmesg.md
      - Dmesg-format: Programming/08-Shell/Dmesg/Dmesg-format.md
      - Dmesg-segfaulting: Programming/08-Shell/Dmesg/Dmesg-segfaulting.md
    - Linux-Kernel-module:
      - Introduction: Programming/08-Shell/Linux-Kernel-module/index.md
plugins:
- search
repo_url: https://github.com/dengking/Linux-OS
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: Linux-OS
site_url: https://dengking.github.io/Linux-OS
theme:
  name: material
