edit_uri: ''
extra_css:
- css/extra.css
google_analytics:
- UA-27795084-5
- mkdocs.org
markdown_extensions:
- toc:
    permalink: '#'
nav:
- Home: index.md
- "Operating-system-\u6982\u8FF0": Operating-system.md
- Unix-standardization-and-implementation: Unix-standardization-and-implementation.md
- Unix-&-Unix-like-&-Linux: Unix-&-Unix-like-&-Linux.md
- Architecture:
  - Architecture-of-computing-system: Architecture/Architecture-of-computing-system.md
- Kernel:
  - Introduction: Kernel/index.md
  - Kernel: Kernel/Kernel(operating-system).md
  - Guide:
    - Linux-OS's-interaction-with-the-hardware:
      - Linux-OS-kernel-is-event-driven: Kernel/Guide/Linux-OS's-interaction-with-the-hardware/Linux-OS-kernel-is-event-driven.md
      - Kernel-control-path-and-reentrant-kernel: Kernel/Guide/Linux-OS's-interaction-with-the-hardware/Kernel-control-path-and-reentrant-kernel.md
      - Linux-OS-interrupt-and-interrupte-handler: Kernel/Guide/Linux-OS's-interaction-with-the-hardware/Linux-OS-interrupt-and-interrupte-handler.md
    - Linux-OS's-multitasking:
      - Multitask: Kernel/Guide/Linux-OS's-multitasking/00-Multitask.md
      - Process-model:
        - Process-model: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-model.md
        - Process-run-model:
          - Process-run-model: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Process-run-model.md
          - Subroutine:
            - Introduction: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Subroutine/index.md
            - Subroutine: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Subroutine/Subroutine.md
            - Call-subroutine:
              - Introduction: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Subroutine/Call-subroutine/index.md
              - Call-stack: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Subroutine/Call-subroutine/Call-stack.md
              - Call-convention: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Subroutine/Call-subroutine/Call-convention.md
            - Activation-tree: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Subroutine/Activation-tree.md
            - Evaluation-strategy:
              - Evaluation-strategy: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Subroutine/Evaluation-strategy/Evaluation-strategy.md
              - Lazy-evaluation: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-run-model/Subroutine/Evaluation-strategy/Lazy-evaluation.md
        - Linux-OS-implementation-of-process-model:
          - Linux-OS-implementation-of-process-model: Kernel/Guide/Linux-OS's-multitasking/Process-model/Linux-OS-implementation-of-process-model/Linux-OS-implementation-of-process-model.md
        - Process-resource:
          - System-resource: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-resource/System-resource.md
          - Process-resource-model: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-resource/Process-resource-model.md
          - Process-memory-model: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-resource/Process-memory-model.md
        - Process-life-cycle: Kernel/Guide/Linux-OS's-multitasking/Process-model/Process-life-cycle.md
        - Thread: Kernel/Guide/Linux-OS's-multitasking/Process-model/Thread.md
      - Sched:
        - Introduction: Kernel/Guide/Linux-OS's-multitasking/Sched/index.md
        - Scheduling(computing): Kernel/Guide/Linux-OS's-multitasking/Sched/Scheduling(computing).md
        - Preemption(computing): Kernel/Guide/Linux-OS's-multitasking/Sched/Preemption(computing).md
        - Kernel-preemption: Kernel/Guide/Linux-OS's-multitasking/Sched/Kernel-preemption.md
        - man-7-sched: Kernel/Guide/Linux-OS's-multitasking/Sched/man-7-sched.md
        - Context-switch: Kernel/Guide/Linux-OS's-multitasking/Sched/Context-switch.md
        - Unix-Scheduler-and-Dispatcher: Kernel/Guide/Linux-OS's-multitasking/Sched/Unix-Scheduler-and-Dispatcher.md
        - Processor-affinity:
          - Introduction: Kernel/Guide/Linux-OS's-multitasking/Sched/Processor-affinity/index.md
    - Memory-management:
      - Memory-management: Kernel/Guide/Memory-management/Memory-management.md
      - Memory-protection: Kernel/Guide/Memory-management/Memory-protection.md
      - Virtual-memory:
        - Virtual-memory: Kernel/Guide/Memory-management/Virtual-memory/Virtual-memory.md
        - Paging: Kernel/Guide/Memory-management/Virtual-memory/Paging.md
        - Unix-system-page-size: Kernel/Guide/Memory-management/Virtual-memory/Unix-system-page-size.md
      - Difference-Between-Paging-and-Segmentation-in-OS: Kernel/Guide/Memory-management/Difference-Between-Paging-and-Segmentation-in-OS.md
    - How-to-understand-linux-kernel-source-code: Kernel/Guide/How-to-understand-linux-kernel-source-code.md
    - Kernel-data-structure: Kernel/Guide/Kernel-data-structure.md
  - Book-Understanding-the-Linux-Kernel:
    - Introduction: Kernel/Book-Understanding-the-Linux-Kernel/index.md
    - Chapter-1-Introduction:
      - Chapter-1-Introduction: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/Chapter-1-Introduction.md
      - 1.1-Linux-Versus-Other-Unix-Like-Kernels: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.1-Linux-Versus-Other-Unix-Like-Kernels.md
      - 1.2-Hardware-Dependency: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.2-Hardware-Dependency.md
      - 1.4-Basic-Operating-System-Concepts: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.4-Basic-Operating-System-Concepts.md
      - 1.6-An-Overview-of-Unix-Kernels: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6-An-Overview-of-Unix-Kernels.md
      - 1.6.1-The-Process-Kernel-Model: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.1-The-Process-Kernel-Model.md
      - 1.6.2-Process-Implementation: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.2-Process-Implementation.md
      - 1.6.3-Reentrant-Kernels: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.3-Reentrant-Kernels.md
      - 1.6.4-Process-Address-Space: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.4-Process-Address-Space.md
      - 1.6.5-Synchronization-and-Critical-Regions: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.5-Synchronization-and-Critical-Regions.md
      - 1.6.6-Signals-and-Interprocess-Communication: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.6-Signals-and-Interprocess-Communication.md
      - 1.6.7-Process-Management: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.7-Process-Management.md
      - 1.6.8-Memory-Management: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.8-Memory-Management.md
      - 1.6.9-Device-Drivers: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/1.6.9-Device-Drivers.md
      - Giant-lock: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-1-Introduction/Giant-lock.md
    - Chapter-2-Memory-Addressing:
      - Chapter-2-Memory-Addressing: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-2-Memory-Addressing/Chapter-2-Memory-Addressing.md
      - 2.1-Memory-Addresses: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-2-Memory-Addressing/2.1-Memory-Addresses.md
      - 2.4-Paging-in-Hardware: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-2-Memory-Addressing/2.4-Paging-in-Hardware.md
      - 2.5-Paging-in-Linux: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-2-Memory-Addressing/2.5-Paging-in-Linux.md
    - Chapter-3-Processes:
      - Chapter-3-Processes: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/Chapter-3-Processes.md
      - 3.1-Processes-and-Lightweight-Processes-and-Threads: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.1-Processes-and-Lightweight-Processes-and-Threads.md
      - 3.2-Process-Descriptor: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2-Process-Descriptor.md
      - 3.2.1-Process-State: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.1-Process-State.md
      - 3.2.2-Identifying-a-Process: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.2-Identifying-a-Process.md
      - 3.2.2.1-Process-descriptors-handling: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.2.1-Process-descriptors-handling.md
      - 3.2.2.2-Identifying-the-current-process: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.2.2-Identifying-the-current-process.md
      - 3.2.2.3-Doubly-linked-lists: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.2.3-Doubly-linked-lists.md
      - 3.2.2.4-The-process-list: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.2.4-The-process-list.md
      - 3.2.2.5-The-lists-of-TASK_RUNNING-processes: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.2.5-The-lists-of-TASK_RUNNING-processes.md
      - 3.2.3-Relationships-Among-Processes: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.3-Relationships-Among-Processes.md
      - 3.2.4-How-Processes-Are-Organized: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.4-How-Processes-Are-Organized.md
      - 3.2.5-Process-Resource-Limits: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.2.5-Process-Resource-Limits.md
      - 3.3-Process-Switch: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.3-Process-Switch.md
      - 3.4-Creating-Processes: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.4-Creating-Processes.md
      - 3.4.2-Kernel-Threads: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.4.2-Kernel-Threads.md
      - Copy-on-write: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/wikipedia-Copy-on-write.md
    - Chapter-4-Interrupts-and-Exceptions:
      - Chapter-4-Interrupts-and-Exceptions: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/Chapter-4-Interrupts-and-Exceptions.md
      - 4.1-The-Role-of-Interrupt-Signals: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.1-The-Role-of-Interrupt-Signals.md
      - 4.2-Interrupts-and-Exceptions: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.2-Interrupts-and-Exceptions.md
      - 4.3-Nested-Execution-of-Exception-and-Interrupt-Handlers: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.3-Nested-Execution-of-Exception-and-Interrupt-Handlers.md
      - 4.4-Initializing-the-Interrupt-Descriptor-Table: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.4-Initializing-the-Interrupt-Descriptor-Table.md
      - 4.5-Exception-Handling: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.5-Exception-Handling.md
      - 4.6-Interrupt-Handling: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/4.6-Interrupt-Handling.md
      - Trap: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-4-Interrupts-and-Exceptions/Trap.md
    - Chapter-6-Timing-Measurements:
      - Chapter-6-Timing-Measurements: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-6-Timing-Measurements/Chapter-6-Timing-Measurements.md
      - 6.1-Clock-and-Timer-Circuits: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-6-Timing-Measurements/6.1-Clock-and-Timer-Circuits.md
    - Chapter-7-Process-Scheduling:
      - Chapter-7-Process-Scheduling: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-7-Process-Scheduling/Chapter-7-Process-Scheduling.md
    - Chapter-8-Memory-Management:
      - Chapter-8-Memory-Management: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-8-Memory-Management/Chapter-8-Memory-Management.md
      - 8.1-Page-Frame-Management: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-8-Memory-Management/8.1-Page-Frame-Management.md
    - Chapter-9-Process-Address-Space:
      - Chapter-9-Process-Address-Space: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-9-Process-Address-Space/Chapter-9-Process-Address-Space.md
      - 9.1-The-Process's-Address-Space.: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-9-Process-Address-Space/9.1-The-Process's-Address-Space.md
      - 9.2-The-Memory-Descriptor: Kernel/Book-Understanding-the-Linux-Kernel/Chapter-9-Process-Address-Space/9.2-The-Memory-Descriptor.md
- Network:
  - Introduction: Network/index.md
  - MAC-address: Network/MAC-address.md
  - Reconnect: Network/Reconnect.md
- Programming:
  - Introduction: Programming/index.md
  - Convention:
    - Conventions: Programming/01-01-Convention/Conventions.md
  - Lib:
    - POSIX:
      - Introduction: Programming/01-02-Lib/organiztion-posix/index.md
  - Common:
    - Time-and-space: Programming/01-03-Common/Unix-programming-time-and-space.md
    - System-call: Programming/01-03-Common/Unix-system-call.md
    - Safety: Programming/01-03-Common/safety.md
    - Capabilities: Programming/01-03-Common/Capabilities.md
    - Path-resolution: Programming/01-03-Common/Path-resolution.md
  - Philosophy:
    - Introduction: Programming/01-philosophy/index.md
    - Everything-is-a-file: Programming/01-philosophy/Everything-is-a-file.md
    - File-descriptor: Programming/01-philosophy/File-descriptor.md
    - Unix-philosophy: Programming/01-philosophy/Unix-philosophy.md
  - File-system:
    - Unix-filesystem: Programming/01-04-File-system/Unix-filesystem.md
    - man-7-file-hierarchy: Programming/01-04-File-system/man-7-file-hierarchy.md
    - Inode: Programming/01-04-File-system/Inode.md
    - man-2-stat: Programming/01-04-File-system/man-2-stat.md
  - Process:
    - Introduction: Programming/02-Process/index.md
    - Credential:
      - man-7-credentials: Programming/02-Process/Credential/man-7-credentials.md
    - IPC:
      - System-V-IPC:
        - man-7-SVIPC: Programming/02-Process/IPC/System-V-IPC/man-7-SVIPC.md
      - POSIX-semaphores: Programming/02-Process/IPC/POSIX-semaphores.md
      - POSIX-message-queues: Programming/02-Process/IPC/POSIX-message-queues.md
    - Thread:
      - pthreads: Programming/02-Process/Thread/pthreads.md
  - IO:
    - Introduction: Programming/03-IO/index.md
    - Input-output: Programming/03-IO/Input-output.md
    - IO-model:
      - Introduction: Programming/03-IO/IO-model/index.md
      - IO-models: Programming/03-IO/IO-model/IO-models.md
    - Stream: Programming/03-IO/Stream.md
    - Bitstream: Programming/03-IO/Bitstream.md
    - VS-stream-VS-fd: Programming/03-IO/VS-stream-VS-fd.md
    - File:
      - Introduction: Programming/03-IO/File/index.md
      - Notify:
        - Inotify:
          - man-7-inotify: Programming/03-IO/File/Notify/Inotify/man-7-inotify.md
        - Fanotify:
          - man-7-fanotify: Programming/03-IO/File/Notify/Fanotify/man-7-fanotify.md
    - Network:
      - Introduction: Programming/03-IO/Network/index.md
    - Notify-via-fd: Programming/03-IO/Notify-via-fd.md
  - Time:
    - Introduction: Programming/03-Time/index.md
  - Signal:
    - Introduction: Programming/04-Signal/index.md
    - Signal-note: Programming/04-Signal/Signal-note.md
  - Virtualization:
    - Introduction: Programming/05-Linux-Virtualization/index.md
    - Virtualization: Programming/05-Linux-Virtualization/Virtualization.md
    - Linux-containers: Programming/05-Linux-Virtualization/Linux-containers.md
    - Linux-namespaces:
      - Introduction: Programming/05-Linux-Virtualization/Linux-namespaces/index.md
      - Linux-Namespaces: Programming/05-Linux-Virtualization/Linux-namespaces/Linux-Namespaces.md
      - man-7-namespaces: Programming/05-Linux-Virtualization/Linux-namespaces/man-7-namespaces.md
    - Linux-control-groups:
      - Introduction: Programming/05-Linux-Virtualization/Linux-control-groups/Control-groups.md
  - Util:
    - Introduction: Programming/06-Util/index.md
    - Log:
      - Linux-log-files: Programming/06-Util/Log/Linux-log-files.md
      - Syslog:
        - Syslog: Programming/06-Util/Log/Syslog/Syslog.md
  - Terminal:
    - Introduction: Programming/Terminal/index.md
  - Computer-errors:
    - Memory-access-error:
      - Introduction: Programming/Computer-errors/Memory-access-error/index.md
      - Double-free:
        - Double-free: Programming/Computer-errors/Memory-access-error/Double-free/Double-free.md
      - Segment-fault:
        - Segmentation-fault: Programming/Computer-errors/Memory-access-error/Segment-fault/Segmentation-fault.md
        - Misalignment:
          - __strcpy_sse2_unaligned:
            - __strcpy_sse2_unaligned: Programming/Computer-errors/Memory-access-error/Segment-fault/Misalignment/__strcpy_sse2_unaligned/__strcpy_sse2_unaligned.md
      - Out-of-bound:
        - Introduction: Programming/Computer-errors/Memory-access-error/Out-of-bound/index.md
  - Kernel-module:
    - Loadable-kernel-module: Programming/07-Linux-Kernel-module/Loadable-kernel-module.md
- Shell-and-tools:
  - Shell:
    - Sched:
      - taskset: Shell-and-tools/08-Shell/Sched/taskset.md
    - Linux-Kernel-module:
      - Introduction: Shell-and-tools/08-Shell/Linux-Kernel-module/index.md
  - Tools:
    - organization-gnu:
      - Introduction: Shell-and-tools/Tools/organization-gnu/index.md
    - Dmesg:
      - Dmesg: Shell-and-tools/Tools/Dmesg/Dmesg.md
      - Dmesg-format: Shell-and-tools/Tools/Dmesg/Dmesg-format.md
      - Dmesg-segfaulting: Shell-and-tools/Tools/Dmesg/Dmesg-segfaulting.md
    - Rsync:
      - Rsync: Shell-and-tools/Tools/Rsync/Rsync.md
    - Debug:
      - Introduction: Shell-and-tools/Tools/Debug/index.md
      - Debugger: Shell-and-tools/Tools/Debug/Debugger.md
      - Trap: Shell-and-tools/Tools/Debug/Trap.md
      - Trace: Shell-and-tools/Tools/Debug/Trace.md
    - Performance:
      - Introduction: Shell-and-tools/Tools/Performance/index.md
plugins:
- search
repo_url: https://github.com/dengking/Linux-OS
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: Linux-OS
site_url: https://dengking.github.io/Linux-OS
theme:
  name: material
