nav:
    - Chapter-2-Memory-Addressing: Chapter-2-Memory-Addressing.md
    - 2.1-Memory-Addresses: 2.1-Memory-Addresses.md
    - 2.4-Paging-in-Hardware: 2.4-Paging-in-Hardware.md\
    - 2.5-Paging-in-Linux: 2.5-Paging-in-Linux.md
    