nav:
    # 综述进程模型、进程的运行模型、概述Linux OS的实现
    - Process-model: Process-model.md
    - Process-run-model: Process-run-model
    - Linux-OS-implementation-of-process-model: Linux-OS-implementation-of-process-model
    
    # 进程所占用的资源以及对资源的管理
    - Process-resource: Process-resource
    # 进程生命周期
    - Process-life-cycle: Process-life-cycle.md
    # 线程
    - Thread: Thread.md