nav:
    - Chapter-3-Processes: Chapter-3-Processes.md
    - 3.1-Processes-and-Lightweight-Processes-and-Threads: 3.1-Processes-and-Lightweight-Processes-and-Threads.md
    - 3.2-Process-Descriptor: 3.2-Process-Descriptor.md
    - 3.2.1-Process-State: 3.2.1-Process-State.md
    - 3.2.2-Identifying-a-Process: 3.2.2-Identifying-a-Process.md
    - 3.2.2.1-Process-descriptors-handling: 3.2.2.1-Process-descriptors-handling.md
    - 3.2.2.2-Identifying-the-current-process: 3.2.2.2-Identifying-the-current-process.md
    - 3.2.2.3-Doubly-linked-lists: 3.2.2.3-Doubly-linked-lists.md
    - 3.2.2.4-The-process-list: 3.2.2.4-The-process-list.md
    - 3.2.2.5-The-lists-of-TASK_RUNNING-processes: 3.2.2.5-The-lists-of-TASK_RUNNING-processes.md
    - 3.4-Creating-Processes: 3.4-Creating-Processes.md
    - Copy-on-write: wikipedia-Copy-on-write.md