nav:
    - Introduction: index.md
    - Scheduling(computing): Scheduling(computing).md
    - Preemption(computing): Preemption(computing).md
    - Kernel-preemption: Kernel-preemption.md
    - man-7-sched: man-7-sched.md
    - Context-switch: Context-switch.md
    - Unix-Scheduler-and-Dispatcher: Unix-Scheduler-and-Dispatcher.md
    - Processor-affinity: Processor-affinity
    
    