nav:
    - Introduction: index.md
    - Credential: Credential
    - Organization-of-process: Organization-of-process
    - Capabilities: Capabilities
    - Sched: Sched
    - IPC: IPC
    - Thread: Thread
    - Exit: Exit
    - Daemon: Daemon
    - Proc-filesystem: Proc-filesystem
    - Tools: Tools
    
    