nav:
    - organization-gnu: organization-gnu
    # 如果程序不知不觉地退出了执行，如何进行分析
    - Dmesg: Dmesg
    # 同步
    - Rsync: Rsync
    # 编程工具相关
    - Debug: Debug
    # 如何统计性能
    - Performance: Performance
    # 如何控制调度
    - Sched: Sched
    # 如何构建应用
    - Build: Build
    
    - Linux-Kernel-module: Linux-Kernel-module