nav:
    - Introduction: index.md
    - gdb-primer: gdb-primer
    - GDB-Command-Reference: GDB-Command-Reference.md
    - Automate: Automate
    - Debug-assembly: Debug-assembly.md
    - gdb-in-action: gdb-in-action.md