nav:
    - Home: index.md
    - Operating-system: Operating-system.md
    - Unix: Unix.md
    - Unix-like: Unix-like.md
    - Linux: Linux.md
    - Architecture: Architecture
    - Kernel: Kernel
    - Programming: Programming